export let products = [
    {
        id: 1,
        title: "The Last Express",
        release: 1997,
        description: "A point-and-click adventure game that takes place on a European train shortly before the outbreak of World War I. The game attempts to simulate real time with a non-linear story and dozens of fully voiced characters.",
        genre: "Adventure",
        price: 6.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696972634/The_Last_Express_ofnx02.jpg",
    },
    {
        id: 2,
        title: "Sinking Island",
        release: 2008,
        description: "A crime-solving adventure game from the creators of Syberia. Players control police investigator Jack Norm as he tries to figure out who killed the billionaire, Walter Jones, on his private island in the Maldives.",
        genre: "Adventure",
        price: 7.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696972694/Sinking_Island_etxef6.jpg",
    },
    {
        id: 3,
        title: "Sherlock Holmes vs. Jack the Ripper",
        release: 2009,
        description: "Sherlock Holmes faces off against history's most notorious serial killer, Jack the Ripper, in an attempt to catch him and put an end to his vicious crimes.",
        genre: "Adventure, Puzzle",
        price: 9.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696972865/Sherlock_Holmes_vs._Jack_the_Ripper_zhwwfq.png",
    },
    {
        id: 4,
        title: "The Sims",
        release: 2000,
        description: "Construct and furnish a home, and then influence the day-to-day lives of its occupants (called Sims) in an isometrical people simulator by Will Wright.",
        genre: "Simulation, Strategy",
        price: 1,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696973116/The_Sims_aomdiq.jpg",
    },
    {
        id: 5,
        title: "The Elder Scrolls V: Skyrim",
        release: 2011,
        description: "The fifth installment in Bethesda's Elder Scrolls franchise is set in the eponymous province of Skyrim, where the ancient threat of dragons, led by the sinister Alduin, is rising again to threaten all mortal races. Only the player, as the prophesied hero the Dovahkiin, can save the world from destruction.",
        genre: "Action-Adventure, Role-Playing",
        price: 39.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696973782/The_Elder_Scrolls_V_Skyrim_dwke9n.png",
    },
    {
        id: 6,
        title: "Crusader Kings",
        release: 2004,
        description: "Crusader Kings is a unique entry in Paradox Interactive's Europa Universalis franchise of strategy games that focuses on family dynasties and the Middle Ages.",
        genre: "Simulation, Strategy",
        price: 49.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696973789/Crusader_Kings_nzpoaz.png",
    },
    {
        id: 7,
        title: "Broken Sword: The Serpent's Curse",
        release: 2013,
        description: "George and Nico return for the fifth game in Charles Cecil's Broken Sword franchise. They embark on an all new adventure that involves an investigation into an armed raid on a Paris gallery. Partially funded by Kickstarter.",
        genre: "Adventure",
        price: 22.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696973853/Broken_Sword_The_Serpent_s_Curse_ssyf8g.jpg",
    },
    {
        id: 8,
        title: "Culpa Innata",
        release: 2007,
        description: "An adventure game set in an elitist utopia, where political correctness, xenophobia and promiscuity all go hand in hand.",
        genre: "Adventure",
        price: 9.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696973961/Culpa_Innata_vdhzzd.jpg",
    },
    {
        id: 9,
        title: "Assassin's Creed II",
        release: 2009,
        description: "A crime-solving adventure game from the creators of Syberia. Players control police investigator Jack Norm as he tries to figure out who killed the billionaire, Walter Jones, on his private island in the Maldives.",
        genre: "Action-Adventure, Platformer",
        price: 9.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696974050/Assassin_s_Creed_II_bale4l.jpg",
    },
    {
        id: 10,
        title: "Full Throttle",
        release: 1995,
        description: "This post-apocalyptic adventure game from LucasArts follows a tough-as-nails biker named Ben, leader of the Polecats, a motorcycle gang.",
        genre: "Adventure",
        price: 14.99,
        stock: 10,
        img: "https://res.cloudinary.com/dkd7rl76b/image/upload/v1696974173/Full_Throttle_sglfr4.jpg",
    }
]